[workspace]
resolver = "3"
members = ["pac"]

[workspace.package]
authors = ["anlang <2682525840@qq.com>"]
edition = "2024"
description = "使用rust语言、stm32f303discovery开发板制作的工程例子，用于嵌入式rust学习"
license = "MIT"
