name: Build and Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main # 触发工作流的源分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 mdBook
      - name: Install mdBook
        run: |
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdBook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin

      # 构建 mdBook
      - name: Build mdBook
        run: |
          cd docs
          mdbook build

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/book # 部署的文件夹
          branch: gh-pages # 目标分支
